<a href="https://colab.research.google.com/github/miguel05mex78-bot/DataScienceMastery/blob/main/Part_1_collect_bioactivity_data_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Computational Drug Discovery [Part 1] Downloading Bioactivity Data from ChEMBL**

Building a machine learning model using the ChEMBL bioactivity data.
Based on coursework from data science professor: Chanin Nantasenamat

---

## **ChEMBL Database**

The [*ChEMBL Database*](https://www.ebi.ac.uk/chembl/) is a database that "brings together chemical, bioactivity and genomic data to aid the translation of genomic information into effective new drugs."

## **Installing libraries**

Install the ChEMBL web service package so that we can retrieve bioactivity data from the ChEMBL Database.

In [1]:
pip install chembl_webresource_client

Collecting chembl_webresource_client
  Downloading chembl_webresource_client-0.10.9-py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.32.4)
Collecting requests-cache~=1.2 (from chembl_webresource_client)
  Downloading requests_cache-1.3.1-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: easydict in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2026.2.25)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (25.4.0)
Collecting cattrs>=22.2 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading cattrs-26.1.0-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.9.2)
Collecting url-normalize>=2.0 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading url_normalize-2.2.1-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.15.0)
Downloading chembl_webresource_client-0.10.9-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.2/55.2 kB 1.7 MB/s eta 0:00:00
Downloading requests_cache-1.3.1-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.2/70.2 kB 2.7 MB/s eta 0:00:00
Downloading cattrs-26.1.0-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 3.1 MB/s eta 0:00:00
Downloading url_normalize-2.2.1-py3-none-any.whl (14 kB)
Installing collected packages: url-normalize, cattrs, requests-cache, chembl_webresource_client
Successfully installed cattrs-26.1.0 chembl_webresource_client-0.10.9 requests-cache-1.3.1 url-normalize-2.2.1

## **Importing libraries**

In [2]:
# Import necessary libraries
import pandas as pd
from chembl_webresource_client.new_client import new_client

## **Search for Target protein**

### **Target search for BCR::ABL1 gene fusion**

The BCR::ABL1 fusion is a genetic abnormality resulting from a translocation between chromosomes 9 and 22, forming the Philadelphia chromosome. This fusion gene encodes a constitutively active tyrosine kinase that drives uncontrolled cell proliferation and survival, contributing to pediatric B-cell acute lymphoblastic leukemia (B-ALL). It is associated with a more aggressive disease course but is treatable with targeted therapies like tyrosine kinase inhibitors (TKIs). Early detection and combining TKIs with chemotherapy have significantly improved outcomes in affected children.

In [3]:
# Target search for coronavirus
target = new_client.target
target_query = target.search('BCR::ABL1')
targets = pd.DataFrame.from_dict(target_query)
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Mus musculus,BCR/ABL1,30.0,False,CHEMBL4523652,"[{'accession': 'P00520', 'component_descriptio...",CHIMERIC PROTEIN,10090
1,[],Mus musculus,Protein cereblon-BCR-ABL,23.0,False,CHEMBL5483195,"[{'accession': 'P00520', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,10090
2,[],Homo sapiens,Bcr/Abl fusion protein,22.0,False,CHEMBL2096618,"[{'accession': 'P00519', 'component_descriptio...",CHIMERIC PROTEIN,9606
3,[],Homo sapiens,Protein cereblon/BCR/ABL,22.0,False,CHEMBL4296137,"[{'accession': 'P00519', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
4,[],Homo sapiens,von Hippel-Lindau disease tumor suppressor/BCR...,20.0,False,CHEMBL4523751,"[{'accession': 'P00519', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
5,[],Homo sapiens,BCR/ABL p210 fusion protein,19.0,False,CHEMBL6105,"[{'accession': 'A1Z199', 'component_descriptio...",CHIMERIC PROTEIN,9606
6,[],Homo sapiens,Tyrosine-protein kinase ABL1,15.0,False,CHEMBL1862,"[{'accession': 'P00519', 'component_descriptio...",SINGLE PROTEIN,9606
7,[],Mus musculus,Tyrosine-protein kinase ABL1,15.0,False,CHEMBL3099,"[{'accession': 'P00520', 'component_descriptio...",SINGLE PROTEIN,10090
8,[],Homo sapiens,Baculoviral IAP repeat-containing protein 2/BC...,15.0,False,CHEMBL4296119,"[{'accession': 'P00519', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
9,[],Homo sapiens,E3 ubiquitin-protein ligase XIAP/BCR/ABL,15.0,False,CHEMBL4296120,"[{'accession': 'P00519', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
10,[],Homo sapiens,Breakpoint cluster region protein,14.0,False,CHEMBL5146,"[{'accession': 'P11274', 'component_descriptio...",SINGLE PROTEIN,9606
11,[],Homo sapiens,Protein cereblon/Tyrosine-protein kinase ABL1,14.0,False,CHEMBL4523750,"[{'accession': 'P00519', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
12,[],Homo sapiens,Ras and Rab interactor 1/Tyrosine-protein kina...,13.0,False,CHEMBL3885630,"[{'accession': 'P00519', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
13,[],Homo sapiens,Transcription factor ETV6/Tyrosine-protein kin...,13.0,False,CHEMBL3885645,"[{'accession': 'P00519', 'component_descriptio...",CHIMERIC PROTEIN,9606
14,[],Homo sapiens,von Hippel-Lindau disease tumor suppressor/ABL1,13.0,False,CHEMBL4523725,"[{'accession': 'P00519', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
15,[],Homo sapiens,CDK5 and ABL1 enzyme substrate 1,13.0,False,CHEMBL6067090,"[{'accession': 'Q8TDN4', 'component_descriptio...",SINGLE PROTEIN,9606
16,[],Homo sapiens,Tyrosine-protein kinase ABL,11.0,False,CHEMBL2111414,"[{'accession': 'P00519', 'component_descriptio...",PROTEIN FAMILY,9606
17,[],Homo sapiens,B-cell receptor-associated protein 31,11.0,False,CHEMBL4295778,"[{'accession': 'P51572', 'component_descriptio...",SINGLE PROTEIN,9606

### **We proceed with the bioactivity data for *"Bcr/Abl fusion protein"* with the ID CHEMBL2096618**

We will assign the fourth entry, which corresponds to the target protein, *"Bcr/Abl fusion protein"* to the ***selected_target*** variable

This will make the BCR::ABL1 fusion protein, as the target for downstream steps. We will use the index number 3 for this entry

In [5]:
selected_target = targets.target_chembl_id[3]
selected_target

'CHEMBL4296137'

Here, we will retrieve only bioactivity data for *"Bcr/Abl fusion protein"* that are reported as IC50 values in nM (nanomolar).

In [6]:
activity = new_client.activity
res = activity.filter(target_chembl_id=selected_target).filter(type="IC50").filter(units="nM")

Put the info into a dataframe named `df`

In [7]:
df = pd.DataFrame.from_dict(res)

Displaying the data frame we just made

In [10]:
df

Empty DataFrame
Columns: []
Index: []

The lower the IC50 nM value, the more potent the drug. Meaning it takes a lower concentration of drug to inhibit 50% of the target protein.

In [26]:
# Ensure all column names are strings and strip whitespace
df.columns = df.columns.astype(str).str.strip()

# Print the cleaned column names
print("Columns after stripping:", df.columns.tolist())

# Check if 'standard_type' exists (case-insensitive check)
column_name = next((col for col in df.columns if col.lower() == "standard_type"), None)

if column_name:
    # Show unique values
    print("Unique values in 'standard_type':", df[column_name].unique())
else:
    print("'standard_type' column not found. Available columns:", df.columns.tolist())

Columns after stripping: []
'standard_type' column not found. Available columns: []

Finally we will save the resulting bioactivity data to a CSV file **bioactivity_data.csv**. We use index=False because we don't want the index to be written to the CSV file.

In [28]:
! mkdir "C:\Users\paola\OneDrive\Documentos\ML_Drug_DEVELOPMENT"
%cd "C:\Users\paola\OneDrive\Documentos\ML_Drug_DEVELOPMENT"

/content/C:\Users\paola\OneDrive\Documentos\ML_Drug_DEVELOPMENT

In [33]:
df.to_csv('bioactivity_data.csv', index=False)

View **bioactivity_data.csv** file in /data.

In [43]:
import pandas as pd
# the file has to be in the same directory as the colab
df = pd.read_csv("bioactivity_data.csv")
#! head bioactivity_data.csv

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\paola\\OneDrive\\Documents\\ML_Drug_DEVELOPMENT\\bioactivity_data.csv'

## **Drop missing values...if any**
If any compounds has missing value for the **standard_value** column then drop it

In [ ]:
df2 = df[df.standard_value.notna()]
df2

## **Data pre-processing of the bioactivity data**

### **Labeling compounds as either being active, inactive or intermediate**
The bioactivity data is in the IC50 unit in nM. The ranges you pick will depend on the target, disease, or other factors.

**Generally** compounds having values of less than 1000 nM will be considered to be **active** while those greater than 10,000 nM will be considered to be **inactive**. As for those values in between 1,000 and 10,000 nM will be referred to as **intermediate**.

**For BCR::ABL1** example we will be more conservative and use IC50 values for Imatinib as a starting point. IC50 values need to be in this range or lower is critical to outperform existing therapies and provide efficacy against potential resistance mutations, such as T315I. We want our drug discovery efforts to be on par or better than existing standard of care therapies like Imatinib. Thus compounds >=1000 will be inactive, <=100 will be active and 100-1000 will be intermediate.

#### **Create a list of bioactivity_class with your selected parameters**

In [ ]:
bioactivity_class = []
for i in df2.standard_value:
  if float(i) >= 1000:
    bioactivity_class.append("inactive")
  elif float(i) <= 100:
    bioactivity_class.append("active")
  else:
    bioactivity_class.append("intermediate")

#### **Iterate the *molecule_chembl_id* to a list**

In [ ]:
mol_cid = []
for i in df2.molecule_chembl_id:
  mol_cid.append(i)

#### **Iterate *canonical_smiles* to a list**

In [ ]:
canonical_smiles = []
for i in df2.canonical_smiles:
  canonical_smiles.append(i)

#### **Iterate *standard_value* to a list**

In [ ]:
standard_value = []
for i in df2.standard_value:
  standard_value.append(i)

#### **Combine the 4 lists into a dataframe called df3**

In [ ]:
data_tuples = list(zip(mol_cid, canonical_smiles, bioactivity_class, standard_value))
df3 = pd.DataFrame( data_tuples,  columns=['molecul e_chembl_id', 'canonical_smiles', 'bioactivity_class', 'standard_value'])

#### **Alternative method**

In [ ]:
selection = ['molecule_chembl_id', 'canonical_smiles', 'standard_value']
df3 = df2[selection]
df3

In [ ]:
pd.concat([df3,pd.Series(bioactivity_class)], axis=1)

Save df3 to CSV file in /data

In [ ]:
df3.to_csv('bioactivity_data_preprocessed.csv', index=False)

---