<a href="https://colab.research.google.com/github/miguel05mex78-bot/DataScienceMastery/blob/main/Random_Forest_Regresor_Diabetes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___
<a href='http://www.kgptalkie.com'><img src='kgptalkie_strips.png'/></a>
___

<center><em>Copyright by KGPTalkie</em></center>
<center><em>For free ML tutorials, visit us at <a href='http://www.kgptalkie.com'>www.kgptalkie.com</a></em></center>

### Random Forest Regressor

#### Diabetes Dataset
- https://www.kaggle.com/uciml/pima-indians-diabetes-database
- The Pima Indians Diabetes Database is a collection of medical records of Pima Indians living in Arizona, USA.
- The dataset contains 442 observations and 10 variables.
- The variables are:
  - age     age in years
  - sex
  - bmi     body mass index
  - bp      average blood pressure
  - s1      tc, T-Cells (a type of white blood cells)
  - s2      ldl, low-density lipoproteins
  - s3      hdl, high-density lipoproteins
  - s4      tch, thyroid stimulating hormone
  - s5      ltg, lamotrigine
  - s6      glu, blood sugar level

In [13]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd

In [3]:
diabetes = datasets.load_diabetes()
# it whows the clues (name of the elements) in the diabetes object
diabetes.keys()

dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename', 'data_module'])

In [4]:
# prints the description of the dataset stored in diabetes.
print(diabetes['DESCR'])

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

:Number of Instances: 442

:Number of Attributes: First 10 columns are numeric predictive values

:Target: Column 11 is a quantitative measure of disease progression one year after baseline

:Attribute Information:
    - age     age in years
    - sex
    - bmi     body mass index
    - bp      average blood pressure
    - s1      tc, total serum cholesterol
    - s2      ldl, low-density lipoproteins
    - s3      hdl, high-density lipoproteins
    - s4      tch, total cholesterol / HDL
    - s5      ltg, possibly log of serum triglycerides level
    - s6      glu, blood sugar level

Note: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times the square root of `n_samples` (i.e. the sum of squares of each column totals 1).

Source URL:
https://www4.stat.ncsu.edu/~boos/var.select/diabetes.html

For more information see:
Bradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.
(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)

In [16]:
# separates the dataset into input features and target values.
X = diabetes.data
y = diabetes.target
pd.DataFrame(X).describe()

,0,1,2,3,4,5,6,7,8,9
count,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02
mean,-2.511817e-19,1.230790e-17,-2.245564e-16,-4.797570e-17,-1.381499e-17,3.918434e-17,-5.777179e-18,-9.042540e-18,9.293722e-17,1.130318e-17
std,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02
min,-1.072256e-01,-4.464164e-02,-9.027530e-02,-1.123988e-01,-1.267807e-01,-1.156131e-01,-1.023071e-01,-7.639450e-02,-1.260971e-01,-1.377672e-01
25%,-3.729927e-02,-4.464164e-02,-3.422907e-02,-3.665608e-02,-3.424784e-02,-3.035840e-02,-3.511716e-02,-3.949338e-02,-3.324559e-02,-3.317903e-02
50%,5.383060e-03,-4.464164e-02,-7.283766e-03,-5.670422e-03,-4.320866e-03,-3.819065e-03,-6.584468e-03,-2.592262e-03,-1.947171e-03,-1.077698e-03
75%,3.807591e-02,5.068012e-02,3.124802e-02,3.564379e-02,2.835801e-02,2.984439e-02,2.931150e-02,3.430886e-02,3.243232e-02,2.791705e-02
max,1.107267e-01,5.068012e-02,1.705552e-01,1.320436e-01,1.539137e-01,1.987880e-01,1.811791e-01,1.852344e-01,1.335973e-01,1.356118e-01

In [18]:

# Splitting the dataset
# X → input features
# y → target values
# 📊 Outputs:
# X_train → training features (70% of data)
# X_test → testing features (30% of data)
# y_train → training labels
# y_test → testing labels
# ⚙️ Parameters:
# test_size=0.3 → 30% of data is used for testing
# random_state=42 → ensures the split is reproducible (same result every time)

X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.3,
                                                    random_state=42)
# This creates a scaling object that will standardize your data.
scaler = StandardScaler()
# Two things happen here:
# fit → learns the mean and standard deviation from X_train
# transform → scales the data using that information
# 📌 After this, your features have:
# mean ≈ 0
# standard deviation ≈ 1
X_train = scaler.fit_transform(X_train)
# 👉 This scales the test data using the same values learned from training data.
# ⚠️ Important:
# You do NOT use fit_transform here
# This avoids data leakage

X_test = scaler.transform(X_test)
# the data is already standardized, check the mean
pd.DataFrame(X_train).describe()

,0,1,2,3,4,5,6,7,8,9
count,3.090000e+02,3.090000e+02,3.090000e+02,3.090000e+02,3.090000e+02,309.000000,3.090000e+02,3.090000e+02,3.090000e+02,3.090000e+02
mean,-2.874364e-17,3.104313e-16,-5.173855e-17,1.437182e-17,-2.299491e-17,0.000000,-5.748728e-17,3.334262e-16,8.048219e-17,-9.197964e-17
std,1.001622e+00,1.001622e+00,1.001622e+00,1.001622e+00,1.001622e+00,1.001622,1.001622e+00,1.001622e+00,1.001622e+00,1.001622e+00
min,-2.343689e+00,-9.464172e-01,-1.919484e+00,-2.371456e+00,-2.302838e+00,-2.437584,-2.148059e+00,-1.607269e+00,-2.219185e+00,-2.938249e+00
25%,-7.722452e-01,-9.464172e-01,-7.063749e-01,-7.910512e-01,-7.249986e-01,-0.651486,-6.712447e-01,-8.460790e-01,-6.820995e-01,-6.915664e-01
50%,9.204899e-02,-9.464172e-01,-1.672151e-01,-1.445218e-01,-9.386266e-02,-0.088832,-1.271554e-01,-8.488872e-02,-5.287657e-02,-2.796468e-04
75%,7.991988e-01,1.056616e+00,6.639895e-01,7.175174e-01,5.659612e-01,0.591587,5.723880e-01,6.763015e-01,6.625647e-01,6.045963e-01
max,2.370643e+00,1.056616e+00,3.292393e+00,2.728942e+00,3.176569e+00,4.131072,3.836924e+00,3.789570e+00,2.749316e+00,2.764868e+00

### Regression Model Building

In [19]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error

In [20]:
rfr = RandomForestRegressor(random_state=42)
rfr.fit(X_train, y_train)
y_predict = rfr.predict(X_test)

In [23]:
import numpy as np
from sklearn.metrics import mean_squared_error


# RMSE
np.sqrt(mean_squared_error(y_test, y_predict))

np.float64(53.473274548857056)

In [22]:
# r2_score
r2_score(y_test, y_predict)

# with the hyperparameter tuning we can improve the r2

0.4703171406480713

In [ ]:
# Hyperparameter Tuning

In [24]:
from sklearn.model_selection import GridSearchCV

In [25]:
params = {
    'n_estimators': [100, 200, 400],
    'max_depth': [10, 20, 30],
    'min_samples_split': [2, 10, 100],
    'min_samples_leaf': [1, 5, 10]}

rfr = RandomForestRegressor()
# n_jobs=-1 to use all the computer cpu on calculating
grid = GridSearchCV(estimator=rfr, param_grid=params, cv=5, n_jobs=-1)
grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'max_depth': [10, 20, 30],
                         'min_samples_leaf': [1, 5, 10],
                         'min_samples_split': [2, 10, 100],
                         'n_estimators': [100, 200, 400]})

In [26]:
grid.best_estimator_

RandomForestRegressor(max_depth=10, min_samples_leaf=10)

In [27]:
y_predict = grid.predict(X_test)

In [28]:
# RMSE
np.sqrt(mean_squared_error(y_test, y_predict))
# it improved because it is lower

np.float64(51.500646896098004)

In [30]:
# r2_score
r2_score(y_test, y_predict)
# this parameter improved

0.508676283808248

In [31]:
plt.figure(figsize=(15,5))
plt.plot(y_test)
plt.plot(y_predict)

NameError: name 'plt' is not defined

# Other Resources
|  ML Course | Description |
|:---|:---|
| [**Data Visualization in Python Masterclass™: Beginners to Pro**](https://bit.ly/udemy95off_kgptalkie) |  Learn to build Machine Learning and Deep Learning models using Python and its libraries like Scikit-Learn, Keras, and TensorFlow. |
| [**Python for Machine Learning: A Step-by-Step Guide**](https://bit.ly/ml-ds-project) | Learn to build Machine Learning and Deep Learning models using Python and its libraries like Scikit-Learn, Keras, and TensorFlow. |
| [**Python for Linear Regression in Machine Learning**](https://bit.ly/regression-python) | Learn to build Linear Regression models using Python and its libraries like Scikit-Learn. |
| [**Introduction to Spacy 3 for Natural Language Processing**](https://bit.ly/spacy-intro) | Learn to build Natural Language Processing models using Python and its libraries like Spacy. |
| [**Advanced Machine Learning and Deep Learning Projects**](https://bit.ly/kgptalkie_ml_projects) | Learn to build Advanced Machine Learning and Deep Learning models using Python and transformer models like BERT, GPT-2, and XLNet. |
| [**Natural Language Processing in Python for Beginners**](https://bit.ly/intro_nlp) | Learn to build Natural Language Processing Projects using Spacy, NLTK, and Gensim, and transformer models like BERT, GPT-2, and XLNet. |
| [**Deployment of Machine Learning Models in Production in Python**](https://bit.ly/bert_nlp) |  Learn to deploy Machine Learning and Deep Learning models using Python and its libraries like Flask, Streamlit, and NGINX. |
| [**R 4.0 Programming for Data Science - Beginners to Pro**](https://bit.ly/r4-ml) | Learn to build Machine Learning and Deep Learning models using R and its libraries like caret, tidyverse, and keras. |